version: "3.8"

services:
  wasi-bot:
    build: .
    container_name: wasi-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - BOT_NAME=WASI BOT
      - MODE=public
      - OWNER_NUMBER=${OWNER_NUMBER}
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - ./session:/app/session
